project:
  type: website
  output-dir: docs

website:
  title: "Daniela Rodriguez-Chavez"
  navbar:
    left:
      - href: about.qmd
        text: About Me
      - research.qmd
      # - publications.qmd
      - community.qmd
      - text: "Resources"
        menu: 
          - href: gschool.qmd
            text: Grad School
      - href: music-theater.qmd
        text: Musical Theater

format:
  html:
    theme: cosmo # flatly, yeti, solar, litera, 
    css: styles.css
    toc: true

editor: visual

