---
title: "Musical Theater"
linkcolor: purple 
title-block-banner: images/musical-theater-2.png
title-block-banner-color: white
include-in-header:
  - text: |
      <style>
      .quarto-title-block .quarto-title-banner {
        background-position-y: center;
        height: 200px;
      }
      </style>
---

#### **Recent Shows I've Seen**

The two memorable shows from April are *Forever Plaid* at the Gateway Theatre ([42nd St. Moon](https://42ndstmoon.org/gateway/)) and *A Strange Loop* at the Toni Rembe Theater ([American Conservatory Theatre](https://www.act-sf.org)).

If you want a story with no plot, minimal set, and a lot of barbershop quartet sound, look no further than *Forever Plaid*. A jukebox musical from the late 80s, this show was essentially a barbershop quarter revue in the form of a show within a show (with some audience interaction). Accompanied by a combo of just piano and bass, the four actors used precise facial movements and tight, but intentional, choreography to bring each character to life, well more like after-life.

Also a show within a show... within a show... is *A Strange Loop*. Those of you who remember \[*title of show\]* might be worried about the potential for a cringe-meta mess, but this show is anything but that. Unapologetically black and queer, the audience is taken through the life of Usher and his six inner thoughts, each of whom plays additional characters throughout the show. A poignant question arising from the show is "what is the line between dramatization and caricature?" A mix of ballads, pop songs, and gospel themes propel the show forward, with the genre of the song often used for satirical enhancement. This is a story that needs to be told yesterday. *Content warning for depictions of verbal abuse, physical abuse, and sexual scenes.*

#### **Recent Shows I've Been In**

UPCOMING: [*Baby Rock*](https://www.hollywoodfringe.org/projects/10500?tab=details) at the Hollywood Fringe Festival

-   May 2024: *Just My Type* at [Chanticleer's Theatre](https://www.chanticleers.org)
-   Oct-Nov 2023: *Tintypes* at [Contra Costa Civic Theatre](https://www.ccct.org)
-   May 2023: *Family Copoli* at Cornell University
-   November 2022: *Baby Rock* at Cornell University
-   November 2022: *Avenue Q* with the [Melodramatics Theatre Company](https://www.melostheatreco.com)

#### **Theaters I Recommend**

There are a lot of great theaters in the Bay Area. Below is a small subset that I frequent. However, for a more full list checkout [Theatre Bay Area](https://www.theatrebayarea.org) or [my own personal list](https://docs.google.com/document/d/1GJsyDc-R5UueHKNIg0VxwXyYjCFLqCkXAYSWuNblP0s/edit?usp=sharing) (where you can see which shows I'm planning on attending).

-   **The Orpheum, Golden Gate Theater, Curran Theatre**. These are all easily accessible by BART at show touring Broadway shows. Check out [NightOutNightOff](https://www.nightoutnightoff.org) for cheaper tickets to these shows.
-   **The Gateway Theatre**. Easily accessible by BART and have cheap tickets on TodayTix.
-   **Berkeley Playhouse.** Easily accesible by AC Transit and very close to campus.
-   **Shotgun Players**. Easily accessible by BART and AC Transit. Tend to have very community engaging shows.

#### 
