---
title: "Maximum Likelihood"
date: 04/30/2024
Keywords: "MLE, Hessian, regression"
---

To start, let's do the first thing many do when trying to learn about a new topic: go to the [Wikipedia page](https://en.wikipedia.org/wiki/Maximum_likelihood_estimation) for it. Let's start with that first paragraph:

*In statistics,* *maximum likelihood estimation (MLE) is a method of estimating the **parameters** of an **assumed probability distribution**, given some observed data. This is achieved by maximizing a **likelihood function** so that, under the assumed statistical model, the observed data is most probable. The point in the **parameter space** that maximizes the likelihood function is called the [maximum likelihood estimate]{.underline}. The logic of maximum likelihood is both intuitive and flexible, and as such the method has become a dominant means of statistical inference. (Taken directly from Wikipedia.)*

Hopefully if it's not intuitive as of yet, it will be once we work through this. Let's break down this first paragraph into various components: parameters, assumed probability distribution, likelihood function, and parameter space.

-   Let's first take about the **assumed probability distribution**. This is the type of distribution you *assume* your data is coming from. For example, for count data, we often use the Poisson distribution, denoted $$ Pois(\lambda) = \frac{\lambda^k e^{-\lambda}}{k!} $$ where $k$ is the number of events that occur in an interval given by rate $\lambda$.

-   In the above example, $\lambda$ is what we call a **parameter**.

But how does MLE actually work? There are three main concepts that I had to wrap my head around

Now, in reality, what does this process look like?

```{r, echo = FALSE}
library(ggplot2)

# Color Scale
mtcars$pc <- predict(prcomp(~wt + mpg, mtcars))[,1]

# Scatter Plot
ggplot(mtcars, aes(wt, mpg, color = pc)) +
  geom_point(shape = 16, size = 5, alpha = 0.4, show.legend = FALSE) +
  theme_minimal() + 
  scale_color_gradient(low = "#0091ff", high = "#f0650e") +
  xlab('Weight (1,000 lbs)') +
  ylab('MPG') +
  ggtitle('Weight Vs. MPG')
```
